---
driver:
  name: vagrant
  network:
    - ["private_network", {type: "dhcp"}]

provisioner:
  name: nodes

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[sensu_test::default]
    attributes:
  - name: example-backend
    driver:
      name: vagrant
      network:
        - ["private_network", {type: "dhcp"}]
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["forwarded_port", {guest: 8081, host: 8081}]
    run_list:
      - recipe[sensu_examples::backend]
  - name: example-agent # Need a running example-backend.
    run_list:
      - recipe[sensu_examples::dummy_app]
      - recipe[sensu_examples::agent]
